//! Configuration management for the Quip Network Node app.

use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::Path;

/// Application configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    /// Node secret (64 hex chars)
    pub node_secret: Option<String>,
    /// Public IP address
    pub public_ip: Option<String>,
    /// Port number (default 20049)
    pub port: u16,
    /// Start node on app launch
    pub auto_start: bool,
    /// Start app on system boot
    pub start_on_boot: bool,
    /// Minimize to system tray on close
    pub minimize_to_tray: bool,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            node_secret: None,
            public_ip: None,
            port: 20049,
            auto_start: false,
            start_on_boot: false,
            minimize_to_tray: true,
        }
    }
}

impl AppConfig {
    /// Load config from the data directory
    pub fn load(data_dir: &Path) -> io::Result<Self> {
        let config_path = data_dir.join("app-settings.json");
        let content = fs::read_to_string(config_path)?;
        serde_json::from_str(&content).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))
    }

    /// Save config to the data directory
    pub fn save(&self, data_dir: &Path) -> io::Result<()> {
        fs::create_dir_all(data_dir)?;
        let config_path = data_dir.join("app-settings.json");
        let content = serde_json::to_string_pretty(self)
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
        fs::write(config_path, content)
    }
}

/// Generate a cryptographically secure 64-character hex secret
pub fn generate_secret() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// Generate the node's config.toml file
pub fn generate_node_config(data_dir: &Path, secret: &str, _public_host: &str, port: u16) -> io::Result<()> {
    let config_content = format!(
        r#"# Quip Network Node Configuration
# Generated by Quip Network Node app

[global]
secret = "{secret}"
listen = "0.0.0.0"
port = {port}
timeout = 3
heartbeat_interval = 15
heartbeat_timeout = 300
verify_ssl = true

[tofu]
enabled = true
trust_db = "{data_dir}/trust.db"

[rest_api]
enabled = false

[cpu]
# Auto-detected
"#,
        secret = secret,
        port = port,
        data_dir = data_dir.display(),
    );

    let config_path = data_dir.join("config.toml");
    fs::write(config_path, config_content)
}
